services:
  postgres:
    image: postgres:16
    container_name: market_sentinel_postgres
    environment:
      POSTGRES_DB: market_sentinel
      POSTGRES_USER: ms_user
      POSTGRES_PASSWORD: ms_pass
    ports:
      - "5433:5432"
    volumes:
      - ms_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: market_sentinel_redis
    ports:
      - "6379:6379"

volumes:
  ms_pgdata:
