server:
  port: 8080

spring:
  application:
    name: SpringMarketAnalysis
  datasource:
    url: jdbc:postgresql://localhost:5433/market_sentinel
    username: ms_user
    password: ms_pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
market:
  scheduler:
    enabled: true
    cron: "0 * * * * MON-FRI" # 6:10 PM weekdays 0 10 18 * * MON-FRI
  alphavantage:
    apiKey: ${ALPHAVANTAGE_API_KEY:}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
